FROM golang:1.18.0-alpine3.15
WORKDIR /go/src/myapp
COPY . .
RUN go get ./
ENV MONGO_DIRECTION=mongodb://mongoadmin:secret@35.223.172.84:27017
ENV RABBIT_DIRECTION=host.docker.internal

CMD ["go","run","main.go"]

#docker build -t rocket1530/subscriber_201807159 .
#docker run -d --name subscriber -e RABBIT_DIRECTION=35.238.6.126 rocket1530/subscriber_201807159